

# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "mail" varchar not null,
  "tel" varchar not null
);

insert into "people" values (default, 'taro', 'taro@yamada', '999-999');
insert into "people" values (default, 'hanako', 'hanako@flower', '888-888');
insert into "people" values (default, 'sachiko', 'sachiko@happy', '777-777');


# --- !Downs

drop table "people" if exists;
